/* Generated by RuntimeBrowser
   Image: /Library/Developer/PrivateFrameworks/CoreSimulator.framework/Versions/A/CoreSimulator
 */
/* And then heavily stripped and annotated by me 🌈
 */

#import <Foundation/Foundation.h>

@class SimRuntime;

NS_ASSUME_NONNULL_BEGIN

typedef NS_ENUM(NSInteger, SimDeviceState) {
    SimDeviceStateCreating,
    SimDeviceStateShutdown,
    SimDeviceStateBooting,
    SimDeviceStateBooted,
    SimDeviceStateShuttingDown
};

@interface SimDevice : NSObject
@property (nonatomic, copy) NSUUID *UDID;
@property (nonatomic, readonly) NSString *name;
@property (nonatomic, readonly) SimRuntime *runtime;
@property (nonatomic, readonly) SimDeviceState state;

- (BOOL)sendPushNotificationForBundleID:(NSString *)bundleID jsonPayload:(NSDictionary *)json error:(NSError **)error;

@end

NS_ASSUME_NONNULL_END
