/* Generated by RuntimeBrowser
    Image: /Library/Developer/PrivateFrameworks/CoreSimulator.framework/Versions/A/CoreSimulator
 */
/* And then heavily stripped and annotated by me 🌈
 */

#import <Foundation/Foundation.h>

NS_ASSUME_NONNULL_BEGIN

@interface SimRuntime : NSObject
@property (nonatomic, copy) NSString *versionString;

@end

NS_ASSUME_NONNULL_END
