/* Generated by RuntimeBrowser
   Image: /Library/Developer/PrivateFrameworks/CoreSimulator.framework/Versions/A/CoreSimulator
 */
/* And then heavily stripped and annotated by me 🌈
 */

#import <Foundation/Foundation.h>

@class SimDeviceSet;

NS_ASSUME_NONNULL_BEGIN

@interface SimServiceContext : NSObject

+ (instancetype)sharedServiceContextForDeveloperDir:(NSString *)developerDirectory error:(NSError **)error;

- (SimDeviceSet *)defaultDeviceSetWithError:(NSError **)error;

@end

NS_ASSUME_NONNULL_END
